on:
  workflow_dispatch:
    inputs:
      debug: 
        type: boolean
        description: Включить debug по VS Code?
        default: true
      artifact_orangefox:
        type: boolean
        description: Загрузить исходный код OrangeFox как артефакт?
        default: true
      free_space:
        type: boolean
        description: Запустить очистку ВМ?
        default: true
      try_zu_bauen:
        type: boolean
        description: Build?
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)

        uses: jlumbroso/free-disk-space@v1.3.1
        if: inputs.free_space
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          tool-cache: false
          swap-storage: true

#      - name: Create Swap File
#        uses: actionhippie/swap-space@v1
#        with:
#          size: 32G

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 32

      - name: Install repo
        run: |
          mkdir -p "$HOME/bin"
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo -o "$HOME/bin/repo"
          chmod +x "$HOME/bin/repo"
          echo "$HOME/bin" >> "$GITHUB_PATH"

      - name: Clone OrangeFox Source
        run: |
          mkdir -p $GITHUB_WORKSPACE/OrangeFox_sync
          cd $GITHUB_WORKSPACE/OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git
          cd sync
          ./orangefox_sync.sh --branch 14.1 --path $GITHUB_WORKSPACE/fox_14.1
          cd $GITHUB_WORKSPACE/fox14.1
          repo sync -c -d --force-sync external/gflags external/guava
      
      - name: Подготовка Source as Artifact
        if: inputs.artifact_orangefox
        run: |
          mkdir $GITHUB_WORKSPACE/artifact
          tar -czf $GITHUB_WORKSPACE/artifact/apelsin.tar.gz -C $GITHUB_WORKSPACE fox_14.1/*
      
      - name: Upload Source as Artifact
        if: inputs.artifact_orangefox
        uses: actions/upload-artifact@v7.0.0
        with:
          name: orange_fox
          path: ${{ github.workspace }}/artifact/apelsin.tar.gz
          retention-days: 3          

      - name: Checkout
        if: inputs.try_zu_bauen
        uses: actions/checkout@v6.0.2
        with:
          path: fox_14.1/device/google/pixels

      - name: Build
        if: inputs.try_zu_bauen
        run: |
          cd $GITHUB_WORKSPACE/fox_14.1/device/google/pixels
          chmod +x ./build.sh
          ./build.sh --family zuma -j1

      - name: Upload Build Artifact
        if: inputs.try_zu_bauen
        uses: actions/upload-artifact@v7.0.0
        with:
          name: orangefox_build_zuma
          path: |
            ${{ github.workspace }}/fox_14.1/builds/*
            ${{ github.workspace }}/fox_14.1/out/target/product/pixels/*.img
            ${{ github.workspace }}/fox_14.1/out/target/product/pixels/*.zip
          retention-days: 7

      - name: Other Artifacts
        if: inputs.try_zu_bauen
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Artifacts
          path: |
            ${{ github.workspace }}/fox_14.1/external/gflags
            ${{ github.workspace }}/fox_14.1/external/guava
          retention-days: 1

      - name: Debbug VS Code
        if: always() && inputs.debug
        uses: fawazahmed0/action-debug-vscode@main


